config/routes.rb
Rails.application.routes.draw do

  unless  Gem::Specification::find_all_by_name('route_translator').any?

    # normal translation scoping
    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      resources :books do
        member do
          get  :admin_view
          post :publish
          post :unpublish
        end
      end

      resources :book_components do
        member do
          post :publish
          post :unpublish
        end
        collection { post :sort }
      end
    end

  else # special routing for localized routes via the route_translator gem

    localized do
      resources :books do
        member do
          get  :admin_view
          post :publish
          post :unpublish
        end
      end

      resources :book_components do
        member do
          post :publish
          post :unpublish
        end
        collection { post :sort }
      end
    end

  end

end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :book_components, dependent: :destroy

  def to_param
    title.present? ? "#{id}-#{title.to_url}" : id
  end

  scope :published, -> { where('published_at IS NOT ?', nil) }
  scope :drafts, -> { where('published_at IS ?', nil) }

  scope :by_recent, -> { order('updated_at desc') }
  scope :alphabetically, -> { order('title') }

end

app/models/book_component.rb
class BookComponent < ActiveRecord::Base

  enum section_type: [ :preface, :acknowledgements, :introduction, :section, :chapter ]

  belongs_to :book, touch: true

  def to_param
    name.present? ? "#{id}-#{name.to_url}" : id
  end

  scope :published, -> { where('published_at IS NOT ?', nil) }
  scope :drafts, -> { where('published_at IS ?', nil) }

  scope :ordered, -> { order('position') }

  ### autocomplete related instance methods
  def book_title
      book.try(:title)
    end
  def book_title=(title)
    if title.present? && Book.where(title: title)
      self.book_id = Book.where(title: title).first.id
    else
      self.book_id = nil
    end
  end

  def chapter_number
    chapter_number = 0
    if section_type == 'chapter'
      self.book.book_components.chapter.ordered.each_with_index do |chapter, index|
        chapter_number = (index + 1) if self.id == chapter.id
      end
    end
    chapter_number
  end

end

app/controllers/book_components_controller.rb
class BookComponentsController < ApplicationController

  before_action :authenticate,                              except: [ :show ]
  before_action -> { require_permission_to 'write_books'},  except: [ :show ]

  def show
    @book_component = BookComponent.find(params[:id])
    @book = @book_component.book
    render layout: 'book'
  end

  def new
    @book_component = BookComponent.new
    @book_component.book_id = params[:book_id] if params[:book_id].present?
    switch_to_admin_layout
  end

  def edit
    @book_component = BookComponent.find(params[:id])
    switch_to_admin_layout
  end

  def create
    @book_component = BookComponent.new( book_component_params )
    if @book_component.book.book_components.count > 1
      @book_component.position = @book_component.book.book_components.ordered.last.position + 1
    else
      @book_component.position = 1
    end
    if @book_component.save
      unless @book_component.section_type == 'section'
        redirect_to @book_component, notice: "The book component was successfully created."
      else
        redirect_to admin_view_book_path(@book_component.book), notice: "The book component was successfully created."
      end
    else
      flash[:warning] = "There was a problem saving this book component."
      render action: "new", layout: 'admin'
    end
  end

  def update
    @book_component = BookComponent.find(params[:id])
    if @book_component.update_attributes( book_component_params )
      unless @book_component.section_type == 'section'
        redirect_to @book_component, notice: "The book component was successfully saved."
      else
        redirect_to admin_view_book_path(@book_component.book), notice: "The book component was successfully saved."
      end
    else
      flash[:warning] = "There was a problem saving this book component."
      render action: "edit", layout: 'admin'
    end
  end

  def destroy
    @book_component = BookComponent.find(params[:id])
    book = @book_component.book
    @book_component.destroy
    redirect_to admin_view_book_path(book), notice: "The book component has been deleted."
  end

  def publish
    book_component = BookComponent.find(params[:id])
    book_component.published_at = Time.now
    if book_component.save
      redirect_to admin_view_book_path(book_component.book), notice: "The book component has been published."
    else
      redirect_to :back, flash: { error: 'There was a problem while publishing this book component.' }
    end
  end

  def unpublish
    book_component = BookComponent.find(params[:id])
    book_component.published_at = nil
    if book_component.save
      redirect_to admin_view_book_path(book_component.book), notice: "The book component has been unpublished and is a draft again."
    else
      redirect_to :back, flash: { error: 'There was a problem while unpublishing this book component.' }
    end
  end

  def sort
    params[:book_component].each_with_index do |id, index|
      BookComponent.update(id, position: index+1)
    end
    render nothing: true
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_component_params
    params.require(:book_component).permit( :book_title, :name, :description, :body, :section_type )
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate,                              except: [ :show ]
  before_action -> { require_permission_to 'write_books'},  except: [ :show ]

  def index
    @books = Book.by_recent.paginate( :page => params[:page], :per_page => 35 )
    switch_to_admin_layout
  end

  def admin_view
    @book = Book.find(params[:id])
    switch_to_admin_layout
  end

  def show
    @book = Book.find(params[:id])
    render layout: 'book'
  end

  def new
    @book = Book.new
    switch_to_admin_layout
  end

  def edit
    @book = Book.find(params[:id])
    switch_to_admin_layout
  end

  def create
    @book = Book.new( book_params )
    if @book.save
      redirect_to books_path, notice: "The book was successfully created."
    else
      flash[:warning] = "There was a problem saving this book."
      render action: "new", layout: 'admin'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes( book_params )
      redirect_to books_path, notice: "The book was successfully saved."
    else
      flash[:warning] = "There was a problem saving this book."
      render action: "edit", layout: 'admin'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "The book has been deleted."
  end

  def publish
    book = Book.find(params[:id])
    book.published_at = Time.now
    if book.save
      redirect_to books_path, notice: "The book has been published."
    else
      redirect_to :back, flash: { error: 'There was a problem while publishing this book.' }
    end
  end

  def unpublish
    book = Book.find(params[:id])
    book.published_at = nil
    if book.save
      redirect_to books_path, notice: "The book has been unpublished and is a draft again."
    else
      redirect_to :back, flash: { error: 'There was a problem while unpublishing this book.' }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit( :title, :subtitle, :author_name, :description, :author_notes )
  end

end

app/views/book_components/_form.html.erb
<%= simple_form_for @book_component, :html => { role: 'form' } do |f| %>
  <%= f.error_notification %>

    <%= f.input :book_title,
                as: :select,
                collection: Book.alphabetically.map(&:title),
                allow_blank: true %>

    <%= f.input :section_type, as: :select, collection: BookComponent.section_types.keys, allow_blank: true %>

    <%= f.input :name, input_html: { size: 45 } %>

    <%= f.input :description, input_html: { cols: 45, rows: 3 } %>

    <%= f.input :body,
                input_html: { class: 'tinymce' } %>
    <%= tinymce selector: 'textarea.tinymce',
                branding: false,
                # context_menu: "link image imagetools table spellchecker",
                height: 550,
                menubar: false, # hiding menu items duplicating icons
                plugins: "lists link image code fullscreen",
                toolbar: "formatselect bold italic strikethrough | bullist numlist | alignleft aligncenter alignright alignnone | link unlink image | undo redo selectall code fullscreen"
    %>                

    <%= f.button :submit, class: 'btn btn-primary' %>

<% end %>

app/views/book_components/_metas.html.erb
<% content_for :search_metas do %>
  <!-- General meta info + SEO -->
  <title><%= "#{book_component.name} | #{book_component.book.title}".html_safe %></title>
  <meta name="description" content="<%= book_component.description %>" />
  <% content_for :canonical_link, link_to('', book_component, rel: 'canonical') %>
<% end %>

app/views/book_components/edit.html.erb
<% content_for :meta_title, "Editing chapter: #{@book_component.name}".html_safe %>
<%= render 'books/header' %>

<%= render 'form' %>

<%= render 'shared/admin_sidebar' %>

app/views/book_components/new.html.erb
<% content_for :meta_title, "New book chapter" %>
<%= render 'books/header' %>

<%= render 'form' %>

<%= render 'shared/admin_sidebar' %>

app/views/book_components/show.html.erb
<%= render 'metas', book_component: @book_component %>

<p id="internal-links"><%= link_to "<span class='glyphicon glyphicon-list'></span> table of contents".html_safe, "#table-of-contents", class: 'btn btn-default' %></p>

<h1>
  <%= content_tag :span, "Chapter #{@book_component.chapter_number}<br />".html_safe, id: 'chapter-number' if @book_component.chapter? %>
  <%= @book_component.name %>
</h1>

<p><%= raw @book_component.body %></p>

<%= render 'books/table_of_contents', book: @book_component.book %>
<%= content_tag :p, link_to("<span class='glyphicon glyphicon-eye-open'></span> admin view".html_safe, admin_view_book_path(@book_component.book), class: 'btn btn-default') if current_user && current_user.is_allowed_to?('write_books') %>

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { role: 'form' } do |f| %>
  <%= f.error_notification %>

    <%= f.input :title, input_html: { size: 45 } %>

    <%= f.input :subtitle,
                hint: "Some books have a longer title displayed on the cover. Like a tagline",
                input_html: { size: 45 } %>

    <%= f.input :author_name, input_html: { size: 45 } %>

    <%= f.input :description, input_html: { cols: 45, rows: 3 } %>

    <%= f.input :author_notes,
                hint: "Only seen by author or editor. Can be used to map out the table of contents",
                input_html: { class: 'tinymce' } %>
    <%= tinymce selector: 'textarea.tinymce',
                branding: false,
                # context_menu: "link image imagetools table spellchecker",
                height: 550,
                menubar: false, # hiding menu items duplicating icons
                plugins: "lists link image code fullscreen",
                toolbar: "formatselect bold italic strikethrough | bullist numlist | alignleft aligncenter alignright alignnone | link unlink image | undo redo selectall code fullscreen"
    %>

    <%= f.button :submit, class: 'btn btn-primary' %>

<% end %>

app/views/books/_header.html.erb
<h1><%= pluralize Book.count, 'Book' %></h1>

<%= render 'books/tab_admin_menu' %>

app/views/books/_metas.html.erb
<% content_for :search_metas do %>
  <!-- General meta info + SEO -->
  <title><%= "Book: #{book.title}" %></title>
  <meta name="description" content="<%= book.description %>" />
  <% content_for :canonical_link, link_to('', book, rel: 'canonical') %>
<% end %>

app/views/books/_tab_admin_menu.html.erb
<ul class="nav nav-tabs" id="admin-menu-tab">
  <%= content_tag :li, link_to(t('new'), new_book_path), ({ class: 'active' } if controller.controller_name.to_s == 'books' && controller.action_name.to_s == 'new' ) %>
  <%= content_tag :li, link_to(t('list'), books_path), ({ class: 'active' } if controller.controller_name.to_s == 'books' && controller.action_name.to_s == 'index' ) %>
  <%= content_tag :li, link_to(t('edit'), '#'), ({ class: 'active' }) if controller.controller_name.to_s == 'books' && controller.action_name.to_s == 'edit' %>
  <%= content_tag :li, link_to('admin view', '#'), ({ class: 'active' }) if controller.controller_name.to_s == 'books' && controller.action_name.to_s == 'admin_view' %>
  <%= content_tag :li, link_to('new chapter', '#'), ({ class: 'active' }) if controller.controller_name.to_s == 'book_components' && controller.action_name.to_s == 'new' %>
  <%= content_tag :li, link_to('edit a chapter', '#'), ({ class: 'active' }) if controller.controller_name.to_s == 'book_components' && controller.action_name.to_s == 'edit' %>
</ul>

app/views/books/_table_of_contents.html.erb
<div id="table-of-contents">
  <h2>Table of Contents</h2>

  <ul>
    <% book.book_components.published.ordered.each do |book_component| %>
      <% unless book_component.section_type == 'section' %>
        <li><%= "#{book_component.chapter_number}." if book_component.chapter? %>
                <%= link_to book_component.name, book_component %>
                <%= link_to( "<span class='glyphicon glyphicon-pencil'></span> edit".html_safe, edit_book_component_path(book_component), class: 'btn btn-xs btn-default') if current_user && current_user.is_allowed_to?('write_books') %></li>
      <% else # no links for section headers %>
        <li class="section-type"><%= book_component.name %>
                <%= link_to( "<span class='glyphicon glyphicon-pencil'></span> edit".html_safe, edit_book_component_path(book_component), class: 'btn btn-xs btn-default') if current_user && current_user.is_allowed_to?('write_books') %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/books/admin_view.html.erb
<% content_for :meta_title, "#{@book.title} - admin view".html_safe %>
<%= render 'books/header' %>

<h1><%= @book.title %></h1>

<h2>Public Description</h2>
<p><%= @book.description %></p>

<table class='table table-striped'>
  <tbody class="draggable" data-update-url="<%= sort_book_components_path %>">
    <% @book.book_components.ordered.each do |book_component| %>
      <tr id="book_component_<%= book_component.id %>">
        <td>
          <%= image_tag 'admin/drag-handle.gif', class: 'handle' %>
          <%= "#{book_component.chapter_number}. " if book_component.chapter? %><%= book_component.section_type != 'section' ? link_to( book_component.name, book_component) : book_component.name %></td>
        <td>
          <% if book_component.published_at %>
            <span class="glyphicon glyphicon-ok"></span>&nbsp;<%= link_to 'unpublish', unpublish_book_component_path(book_component), class: 'btn btn-xs btn-default', method: :post %>
          <% else %>
            <span class="glyphicon glyphicon-remove"></span>&nbsp;<%= link_to 'publish', publish_book_component_path(book_component), class: 'btn btn-xs btn-default', method: :post %>
          <% end %>
        </td>
        <td>
          <%= link_to "<span class='glyphicon glyphicon-pencil'></span> edit".html_safe, edit_book_component_path(book_component), class: 'btn btn-xs btn-primary' %><%= link_to "<span class='glyphicon glyphicon-trash'></span> delete".html_safe, book_component, method: :delete, data: { confirm: 'are you sure?' }, class: 'btn btn-xs btn-danger' %>
          <%= book_component.section_type %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "<span class='glyphicon glyphicon-pencil'></span> edit book".html_safe, edit_book_path(@book), class: 'btn btn-default' %><%= link_to "<span class='glyphicon glyphicon-plus'></span> New Chapter".html_safe, new_book_component_path( book_id: @book.id ), class: 'btn btn-default' %></p>

<h2>Private Author Notes</h2>
<%= raw @book.author_notes %>

<%= render 'shared/admin_sidebar' %>

app/views/books/edit.html.erb
<% content_for :meta_title, "Editing #{@book.title}".html_safe %>
<%= render 'header' %>

<%= render 'form' %>

<%= render 'shared/admin_sidebar' %>

app/views/books/index.html.erb
<% content_for :meta_title, "List of books" %>
<%= render 'books/header' %>

<%= will_paginate @books, inner_window: 2 %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>title</th>
      <th>author</th>
      <th>published?</th>
      <th><%= t('actions') %></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author_name %></td>
        <td>
          <% if book.published_at %>
            <span class="glyphicon glyphicon-ok"></span>&nbsp;<%= link_to 'unpublish', unpublish_book_path(book), class: 'btn btn-xs btn-default', method: :post %>
          <% else %>
            <span class="glyphicon glyphicon-remove"></span>&nbsp;<%= link_to 'publish', publish_book_path(book), class: 'btn btn-xs btn-default', method: :post %>
          <% end %>
        </td>
        <td>
          <%= link_to "<span class='glyphicon glyphicon-pencil'></span> edit".html_safe, edit_book_path(book), class: 'btn btn-xs btn-default' %><%= link_to "<span class='glyphicon glyphicon-eye-open'></span> admin view".html_safe, admin_view_book_path(book), class: 'btn btn-xs btn-default' %><%= link_to "<span class='glyphicon glyphicon-trash'></span> delete".html_safe, book, method: :delete, data: { confirm: 'are you sure?' }, class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @books, inner_window: 2 %>

<%= link_to "<span class='glyphicon glyphicon-plus'></span> New Book".html_safe, new_book_path, class: 'btn btn-default' %>

<%= render 'shared/admin_sidebar' %>

app/views/books/new.html.erb
<% content_for :meta_title, "New book".html_safe %>
<%= render 'header' %>

<%= render 'form' %>

<%= render 'shared/admin_sidebar' %>

app/views/books/show.html.erb
<%= render 'metas', book: @book %>

<p><%= @book.description %></p>

<%= render 'table_of_contents', book: @book %>
<%= content_tag :p, link_to("<span class='glyphicon glyphicon-eye-open'></span> admin view".html_safe, admin_view_book_path(@book), class: 'btn btn-default') if current_user && current_user.is_allowed_to?('write_books') %>

app/views/layouts/book.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <%= yield :search_metas %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <%= favicon_link_tag '/favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>


  <body>

    <div class="container">

      <div class="row" id="site-header">
        <div id='big-header' class="col-xs-12">
          <h1 id="book-title"><%= @book.title %></h1>
          <h2 id="book-subtitle"><%= @book.subtitle %></h2>
          <h2 id="book-author">by <%= @book.author_name %></h2>
        </div>
      </div>

      <div class="row">
        <article class="col-xs-12">
          <%= render 'shared/flash_messages' %>
          <%= yield %>
        </article>
      </div>

    </div> <!-- container class -->

    <div class="row">
      <div id="footer">
        <div class="container">
          <div class="col-xs-12" id="footer">

          </div>
        </div>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>